'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace GoogleCalendarAPI


    Partial Public Class AppointmentSynchronizer

        ''' <summary>
        ''' innerAppointmentDataSource control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected innerAppointmentDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    End Class
End Namespace
