'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace GoogleCalendarAPI


    Partial Public Class [Default]

        ''' <summary>
        ''' Head1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' AppointmentSynchronizer1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AppointmentSynchronizer1 As Global.GoogleCalendarAPI.AppointmentSynchronizer

        ''' <summary>
        ''' ASPxRoundPanel2 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxRoundPanel2 As Global.DevExpress.Web.ASPxRoundPanel

        ''' <summary>
        ''' lbCalendars control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected lbCalendars As Global.System.Web.UI.WebControls.ListBox

        ''' <summary>
        ''' ASPxRoundPanel1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxRoundPanel1 As Global.DevExpress.Web.ASPxRoundPanel

        ''' <summary>
        ''' timeZoneEdit1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected timeZoneEdit1 As Global.DevExpress.Web.ASPxScheduler.ASPxTimeZoneEdit

        ''' <summary>
        ''' ASPxScheduler1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxScheduler1 As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler
    End Class
End Namespace
